permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
name:         Denis Bakhvalov
description:  Performance optimizations and analysis in C/C++
url:          https://easyperf.net
enforce_ssl:  easyperf.net
author:
  name: Denis Bakhvalov
  twitter: dendibakh
timezone: America/New_York
